on:
  push:
    tags:
      - 'v*'

env:
  DWC_VERSION: ${{ inputs.dwc_version || 'v3.5.3' }}
  VERSION: ${{ github.ref_name }}

name: Build MillenniumOS UI for Release
jobs:
  build-and-release:
    name: Build and Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
      - name: Checkout Duet Web Control
        uses: actions/checkout@v4
        with:
          repository: Duet3D/DuetWebControl
          ref: ${{ env.DWC_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: src/plugins/MillenniumOS

      - name: Build MillenniumOS UI Release
        run: |
          src/plugins/MillenniumOS/dist/release.sh

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: MillenniumOS UI ${{ env.VERSION }}
          draft: true
          body: |
            This release of MillenniumOS UI is built for Duet Web Control ${{ env.DWC_VERSION }}.
            it will not work with other versions of Duet Web Control! Make sure you're running
            the correct version of DWC before installing this release.
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            dist/*.zip
